name: hello-world
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: cd ..
      - run: ls
      - run: pwd
      - run: cd ..
      - run: ls
      - run: pwd
      - run: ls
      - run: make say-hello
